apiVersion: v2
name: dmarc-service
description: Self-hosted, multi-tenant DMARC / TLS-RPT report collector and viewer
type: application
version: 0.1.0
appVersion: "0.1.0"
home: https://github.com/pescheck/dmarc-service
sources:
  - https://github.com/pescheck/dmarc-service
